### ISSUE TITLE
一些意见

### ISSUE THREAD

**Issue by Nenot233** [LambdaYH/zhenxun_plugin_weibo#4]
关于微博检测问题，可以检测上一条为准

因为像调试BOT需要重启的时候就检测不到就不推送了←**目前遇到的问题**

或者有更好的检测方式

**Comment by LambdaYH** [comment]
理论上来说重启BOT不会导致该推送的微博不被推送，如果发生这种情况，有以下几种可能
1. 第一次启动。第一次启动时会忽略先前的所有微博防止刷屏。
2. 非第一次启动但人为删除了'TEMP_PATH / "weibo"'文件夹。
3. 在重启BOT之前已经获取到了新的微博，但是获取到微博至发送消息之间的时间段你重启了Bot
4. 重启之前微博发送时间在过去的2小时内，此时还未获取微博，但重启后微博发送时间在过去2h之前了，因为会忽略一切2h前发送的微博，所以这样也不会推送新的。
5. 'm.weibo.cn'与'weibo.com'两个站点微博有时会出现不同步问题，甚至极少情况会获取不到部分微博（加cookie可以有效缓解）。

不知道你遇到的情况是否在上述之中？

关于检测上一条的话，因为即使以检测上一条作为判断更新的依据，也是在同样的时间节点存储记录，还会有置顶等的干扰。而且目前是将获取到的最近n条记录（api一次性获取微博数的上限）的，也包括上一条的信息。

**Comment by Nenot233** [comment]
1. 第4点，我是把时间调整1分钟检测一次
@scheduler.scheduled_job("interval", seconds=60, jitter=10)
2. 微博是11:58分发送
![image](https://user-images.githubusercontent.com/108965579/203933009-92bf280f-33d0-4a43-8a9e-5f9c2403e0c2.png)
3.cookie确认有效
4.该微博推送2个群都没有收到信息，且确认开启了微博推送

**Comment by Nenot233** [comment]
微博链接
https://weibo.com/1907840615/MgDMgibFu

**Comment by LambdaYH** [comment]
如果正确获取到了微博会有`成功获取@xxx的新微博`，没获取到会有`未检测到@xxxx的新微博`的日志，希望可以定位到那儿发送日志看看。

**Comment by Nenot233** [comment]
请问一下真寻在哪找这个日志？
"data/log"?
2022-11-25.log这个文件并未能找到未检测到@xxxx的新微博的日志

**Comment by LambdaYH** [comment]
![image](https://user-images.githubusercontent.com/13503375/203937565-7ee79f5a-c2fc-42f5-88e0-d1eff008a86f.png)

如果没有可以看看启动时候插件有没有被正确加载

**Comment by Nenot233** [comment]
在真寻帮助里面，能看得见微博推送这个插件，但是log上面确实没有
[2022-11-25.log](https://github.com/LambdaYH/zhenxun_plugin_weibo/files/10090317/2022-11-25.log)

**Comment by LambdaYH** [comment]
emmmm，你这个日志怎么没有正常启动后的状态，我搜`weibo`都没搜到相关的东西，如果正常的话是会有`Succeeded to import zhenxun_plugin_weibo`的
![image](https://user-images.githubusercontent.com/13503375/203946759-15432490-0568-49af-9fbc-cdd2c3d85bcf.png)

**Comment by Nenot233** [comment]
我在等等看，会不会出现这个情况，有的话在反馈吧，目前是已经重启了
![image](https://user-images.githubusercontent.com/108965579/203947500-720a8547-8483-49e8-912e-17c8d27fc9bc.png)
![image](https://user-images.githubusercontent.com/108965579/203947527-0987ee21-3064-4a91-9052-1ea0a70aa3cc.png)

**Comment by Nenot233** [comment]
11-29 08:01:07 [ERROR] zhenxun_plugin_weibo | 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\__init__.py", line 233, in _
    latest_weibos = await spider.get_latest_weibos()
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\weibo_spider.py", line 386, in get_latest_weibos
    wb = await self.get_one_weibo(w)
> File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\weibo_spider.py", line 360, in get_one_weibo
    retweet = self.parse_weibo(retweeted_status)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\weibo_spider.py", line 295, in parse_weibo
    weibo["screen_name"] = weibo_info["user"]["screen_name"]
TypeError: 'NoneType' object is not subscriptable
询问一下，这个报错是因为我设置有问题吗？仅修改了weibo_config.yaml和_init_.py

**Comment by LambdaYH** [comment]
微博用户id丢过来看看

**Comment by Nenot233** [comment]
Nenot104

**Comment by LambdaYH** [comment]
![image](https://user-images.githubusercontent.com/13503375/204421570-b851eb05-867f-488d-af41-e9ac7a4971e3.png)
测试了一下没发现什么问题，估计你config里user_id填错了

**Comment by Nenot233** [comment]
但是能正常推送

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/204422392-d757dc52-24d2-45e3-9fa5-256fbdcfba24.png)
但是一检测就一片报错

**Comment by Nenot233** [comment]
weibo-133:
  desciption: 测试微博推送
  enable_on_default: False
  format: 0
  users:
  - user_id: '2645054143'
    nickname: 测试
    filter_retweet: false
    filter_words: [
    微博抽奖平台
    ]
这是config配置

**Comment by LambdaYH** [comment]
emmm
![image](https://user-images.githubusercontent.com/13503375/204425170-bebccbee-9411-4e47-a871-9d7c233d9257.png)
![image](https://user-images.githubusercontent.com/13503375/204425219-e6311b1c-dbea-423e-9c42-33689b6cfb50.png)
我没办法复现

**Comment by Nenot233** [comment]
这份iss里面有个log有敏感信息，能删掉么）
