### ISSUE TITLE
似乎无法识别转发问题

### ISSUE THREAD

**Issue by Nenot233** [LambdaYH/zhenxun_plugin_weibo#7]
yaml文件配置
weibo-banyisheng:
  desciption: 阿板微博推送
  enable_on_default: False
  format: 0
  users:
  - user_id: '1907840615'
    nickname: 阿板
    filter_retweet: true
    filter_words: [
    微博抽奖平台
    ]
    
实际效果
![image](https://user-images.githubusercontent.com/108965579/213386327-512bff93-6df2-4f0b-941b-3ff4f15de177.png)
实际情况
![image](https://user-images.githubusercontent.com/108965579/213386401-a1a17e48-d680-45be-aa2a-4e1836de34ed.png)

**Comment by LambdaYH** [comment]
https://github.com/LambdaYH/zhenxun_plugin_weibo/commit/2a6705f2193ecc1ee57b5def30df78256dbc63a1
这似乎是把该用户评论的微博当作他自己发的微博推送出来了，简单修了下
还没怎么测试过，先开着这个issue

**Comment by Nenot233** [comment]
还是会遇到这个情况

**Comment by Nenot233** [comment]
![image](https://user-images.githubusercontent.com/108965579/214212603-3c7fa353-52e9-4d5c-9cba-e8b6c0a5ef22.png)
似乎是因为评论（转发?）

**Comment by Nenot233** [comment]
自己转发的不会推送，类似上面这个情况就会推送原微博

**Comment by LambdaYH** [comment]
https://github.com/LambdaYH/zhenxun_plugin_weibo/commit/cbacce16920287f88e5909af1b934a3c65e0e49c

**Comment by Nenot233** [comment]
01-30 17:22:57 [ERROR] zhenxun_plugin_weibo | 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\__init__.py", line 236, in _
    latest_weibos = await spider.get_latest_weibos()
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\weibo_spider.py", line 362, in get_latest_weibos
    wb = await self.get_one_weibo(w)
> File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\weibo_spider.py", line 334, in get_one_weibo
    retweet = self.parse_weibo(retweeted_status)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\weibo_spider.py", line 276, in parse_weibo
    weibo["screen_name"] = weibo_info["user"]["screen_name"]
TypeError: 'NoneType' object is not subscriptable
01-30 17:22:57 [ERROR] zhenxun_plugin_weibo | 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\__init__.py", line 236, in _
    latest_weibos = await spider.get_latest_weibos()
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\weibo_spider.py", line 362, in get_latest_weibos
    wb = await self.get_one_weibo(w)
   File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\weibo_spider.py", line 334, in get_one_weibo
    retweet = self.parse_weibo(retweeted_status)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_weibo\weibo_spider.py", line 276, in parse_weibo
    weibo["screen_name"] = weibo_info["user"]["screen_name"]
TypeError: 'NoneType' object is not subscriptable

我会冒出这段报错，有问题吗？

**Comment by LambdaYH** [comment]
https://github.com/LambdaYH/zhenxun_plugin_weibo/commit/a94a0d0e412d391d561d11c323c50d6a4f71b7fd
